export enum EArtworkTags {
  SHAPES = "Shapes",
  LOGOS = "Logos",
  ICONS = "Icons",
  ANIMATIONS = "Animations",
  ILLUSTRATIONS = "Illustrations",
  SIMPLE = "Simple",
  COMPLEX = "Complex",
  THREE_D = "3D",
  TEXT_ART = "Text Art",
  SCENES = "Scenes",
  NATURE = "Nature",
  UNDERWATER = "Underwater",
  SPACE = "Space",
  PLANETS = "Planets",
  ELEMENTS = "Elements",
  HOLIDAYS = "Holidays",
  SEASONAL = "Seasonal",
  GRAPHICS = "Graphics",
  GAMES = "Games",
  FILM_SERIES_VIDEOS = "Film / Series / Videos",
  PIXEL_ART = "Pixel Art",
  INPUTS = "Inputs (text, button, etc.)",
  DEV = "DEV",
}
